### ISSUE TITLE
Integrate Basic Auth Extension

### ISSUE THREAD

**Issue by DominikPinsel** [catenax-ng/product-edc#89]
At the time of writing the Data Management API of the Control Plane is secured via Api Key. This Api-Key is currently part of the documentation. By using the Basic Auth extension this secret can be moved to the Key Vault.

This issue includes
- integration of the existing Basic Auth Extension from the EDC Repository
- update of the control plane documentation
- update of the control plane settings in Helm

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by florianrusch-zf** [comment]
@DominikPinsel i would recommend to postpone this feature a little bit. Currently the api-wrapper only supports token based auth for the data management api. I would recommend to upgrade the api-wrapper first to ensure we don't have any incompatibility between our two components.

I don't know, when we will do this upgrade on the api-wrapper side, because there are still a few other open issues with higher prio in my eyes.

**Comment by DominikPinsel** [comment]
@florianrusch-zf Thanks for pointing this out. Then let's postpone the integration for now. Maybe we can reactivate this issue after a first release. This should give us some time to align all components again. I will close this issue 'till then :)
